
import Sidebar from "@/components/Sidebar/Sidebar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Next Auth Dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="min-h-screen my-2">
      <div className="flex flex-col lg:flex-row">
        <div className="lg:w-[20%]">
          <Sidebar />
        </div>
        <div className="w-full lg:w-[80%] bg-slate-100 rounded-xl lg:ml-2 p-4 mt-16 lg:mt-0">
          {children}
        </div>
      </div>
    </div>
  );
}
